version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    # Keep both direct and indirect dependency updates by default
    allow:
      - dependency-type: "all"
    # ESLint v9 reuires Node.js 20+, but the project uses Node.js 18 in production
    ignore:
      - dependency-name: "eslint"
        versions: [">=9"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - dependencies
    # Optionally enabled security-only updates for GitHub Actions
    allow:
      - dependency-type: "direct"
